### PR TITLE
Create bobby

### PR DESCRIPTION
**Pull request by jacobroschen**

### CODE REVIEW

**Comment by bohawi** [comment]
@nuibot do something

**Comment by jacobroschen** [comment]
@bohawi, an invalid command was used. Please use one of the commands listed in the NuiBot Readme

**Comment by bohawi** [comment]
@nuibot please merge and bump

**Comment by jacobroschen** [comment]
@bohawi, an invalid command was used. Please use one of the commands listed in the NuiBot Readme

**Comment by bohawi** [comment]
@nuibot Please merge and bump

**Comment by jacobroschen** [comment]
@bohawi, you do not have permission to merge into this branch

**Comment by bohawi** [comment]
@nuibot Please merge and bump

**Comment by jacobroschen** [comment]
@bohawi, you do not have permission to merge into this branch

**Comment by bohawi** [comment]
@nuibot Please merge and bump

**Pull request merged**
